spring.application.name=papasud

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-da4oafbl550s738h5b80-a.oregon-postgres.render.com:5432/papasud_xb18}
spring.datasource.username=${DB_USER:hackatonpapasud}
spring.datasource.password=${DB_PASSWORD:2TJgSlMK0xxlVUDUB4ojuiQZuigugyp5}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

openai.api.key=${OPENAI_API_KEY:dummy-key}
